version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    container_name: rule_backend
    ports:
      - "8000:8000"
    volumes:
      - ./outputs:/app/outputs
      - ./backend:/app/backend
    environment:
      - PYTHONPATH=/app
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    container_name: rule_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:8000

  ollama:
    image: ollama/ollama:latest
    container_name: rule_ollama
    ports:
      - "11434:11434"
    volumes:

      - ./configs/llm_config.json:/app/configs/llm_config.json
      # Mount local Ollama models directory from host machine
      # Windows path (adjust the path according to your Ollama installation)
      - ~/.ollama:/root/.ollama
      # Alternative for Windows: C:\Users\{username}\.ollama:/root/.ollama
      # For WSL: /home/{username}/.ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    # Uncomment the following lines if you have an NVIDIA GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  node_modules:
  outputs:
