version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
>>>>>>> 686e149d156889e4f77fcc7eb84ec693b775b1cf
    container_name: rule_backend
    ports:
      - "8000:8000"
    volumes:
      - ./outputs:/app/outputs
      - ./backend:/app/backend
    environment:
      - PYTHONPATH=/app
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
>>>>>>> 686e149d156889e4f77fcc7eb84ec693b775b1cf
    container_name: rule_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  node_modules:
  outputs:
