version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: resume_parser_backend
    ports:
      - "8000:8000"
    volumes:
      - ./outputs:/app/outputs
      - ./backend:/app/backend
    environment:
      - PYTHONPATH=/app
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: resume_parser_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  node_modules:
  outputs:
